
name: build brickrail

on: [push]

env:
  GODOT_VERSION: 3.5
  EXPORT_NAME: Brickrail
  PROJECT_PATH: brickrail-gui

jobs:
  ble-server-linux:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run pyinstaller
        run: |
          pyinstaller ble_server-linux.spec
      - name: upload dist
        uses: actions/upload-artifact@v3
        with:
          name: ble-server-linux
          path: dist/ble-server-linux

  ble-server-windows:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run pyinstaller
        run: |
          pyinstaller ble_server-windows.spec
      - name: upload dist
        uses: actions/upload-artifact@v3
        with:
          name: ble-server-windows
          path: dist/ble-server-windows

  export-windows:
    name: GUI Windows Export
    needs: ble-server-windows
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot -v --export "Windows Desktop" ../build/windows/$EXPORT_NAME.exe
      - name: Download ble-server artifact
        uses: actions/download-artifact@v3
        with:
          name: ble-server-windows
          path: build/windows/ble-server-windows
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: brickrail-windows
          path: build/windows

  export-linux:
    name: GUI Linux Export
    needs: ble-server-linux
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:3.5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot -v --export "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64
      - name: Download ble-server artifact
        uses: actions/download-artifact@v3
        with:
          name: ble-server-linux
          path: build/linux/ble-server-linux
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: brickrail-linux
          path: build/linux